apiVersion: v2
name: sonarr
description: A Helm chart for Sonarr - Smart PVR for newsgroup and bittorrent users
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - sonarr
  - media
  - pvr
  - automation
home: https://github.com/chillincool/charts
sources:
  - https://github.com/chillincool/containers
  - https://github.com/Sonarr/Sonarr
maintainers:
  - name: chillincool
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
