apiVersion: v2
name: sonarr
description: A Helm chart for Sonarr
type: application
version: 0.2.0
# Updated: 2025-11-30 v2
appVersion: "latest"
keywords:
  - sonarr
  - media
  - pvr
  - automation
home: https://github.com/chillincool/charts
sources:
  - https://github.com/chillincool/containers
  - https://github.com/Sonarr/Sonarr
maintainers:
  - name: chillincool
dependencies:
  - name: common
    version: 1.1.0
    repository: file://../common
