apiVersion: v2
name: recyclarr
description: A Helm chart for Recyclarr - automated quality profile management for Radarr/Sonarr
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - recyclarr
  - radarr
  - sonarr
  - quality
  - profiles
home: https://github.com/chillincool/charts
sources:
  - https://github.com/chillincool/containers
maintainers:
  - name: chillincool
dependencies:
  - name: common
    version: 1.1.8
    repository: file://../common