apiVersion: v2
name: lidarr
description: A Helm chart for Lidarr - A music collection manager for Usenet and BitTorrent users
type: application
version: 0.2.4
# Updated: 2025-11-30 v3
appVersion: "67c49d9740a44996c5b6108e38d1d1987abd125f"
keywords:
  - lidarr
  - media
  - music
  - automation
home: https://github.com/chillincool/charts
sources:
  - https://github.com/chillincool/containers
  - https://github.com/Lidarr/Lidarr
maintainers:
  - name: chillincool
dependencies:
  - name: common
    version: 1.1.4
    repository: file://../common
