apiVersion: v2
name: prowlarr
description: A Helm chart for Prowlarr - An indexer manager/proxy for Usenet and BitTorrent
type: application
version: 0.2.9
# Updated: 2025-11-30 v3
appVersion: "2.3.0.5236"
keywords:
  - prowlarr
  - media
  - indexer
  - automation
home: https://github.com/chillincool/charts
sources:
  - https://github.com/chillincool/containers
  - https://github.com/Prowlarr/Prowlarr
maintainers:
  - name: chillincool
dependencies:
  - name: common
    version: 1.1.6
    repository: file://../common
